jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1-node
    steps:
      - checkout
      - run: ruby --version
      - run: bundle install
      - run: bundle exec rspec
      - run: rspec