jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1-node
      - image: circleci/postgres:9.6.2-alpine
    steps:
      - checkout
      - run: ruby --version
      - run: bundle install
      - run: bundle exec rspec