version: 2.1
orbs:
  postgres-rspec: sbc-orbs/postgres-rspec@0.0.28
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1-node
    steps:
      - checkout
      - run: ruby --version
      - run: bundle install

